stages:
  make_dataset:
    cmd: python src/data/make_dataset.py
    deps:
      - src/data/make_dataset.py
      - params.yaml
      - data/raw/creditcard.csv
    outs:
      - data/processed/train.csv
      - data/processed/test.csv

  build_features:
    cmd: python src/features/build_features.py
    deps:
      - src/features/build_features.py
      - params.yaml
      - data/processed/train.csv
      - data/processed/test.csv
    outs:
      - data/processed/train_features.csv
      - data/processed/test_features.csv

  train_model:
    cmd: python src/models/train_model.py
    deps:
      - src/models/train_model.py
      - params.yaml
      - data/processed/train_features.csv
      - data/processed/test_features.csv
    outs:
      - models/rf_model.pkl
