# Configuration file for fraud detection MLOps pipeline

data:
  raw_path: "data/raw/creditcard.csv"
  processed_dir: "data/processed"
  test_size: 0.2
  random_state: 42

model:
  type: "RandomForestClassifier"
  n_estimators: 100
  max_depth: 10
  class_weight: "balanced"
  random_state: 42

train:
  experiment_name: "fraud-detection-mlflow"
  threshold: 0.5
  random_state: 42

paths:
  model_dir: "models"
  figures_dir: "reports/figures"
